version: '3'
services:
  # myapp:
  #   container_name: locations
  #   restart: always
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   links:
  #     - redis
  #     - mongo
  mongo:
    container_name: LOCATIONS_MONGO
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - ./data:/var/lib/mongodb
  redis:
    container_name: LOCATIONS_REDIS
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/var/lib/redis